baseURL = "http://familytrips.life/"
title = "F a m i l y T r i p s . l i f e"
subtitle = "Make travel fun and easy with family"
languageCode = "en-us"
# preservetaxonomynames = true
theme = "hugo-travelify-theme"
GoogleAnalytics = "" # Add your own Google analytics code here in the format UA-XXXXXXXX-X
canonifyURLs = true

# rssURI = "feed/" #deprecated feature

[params]
    # Tell me who you are
    author = "midniteblogger"
    site_description = "Make travel fun and easy with family"
    copyright  = "Copyright"
#    avatar = "avatar.png"
    logo = "logo.jpg"
    title_in_logo = true # set to true if you want the title along with the logo
    disable_mathjax = true # set to true to disable MathJax

    # Format dates with Go's time formatting
    date_format = "02 January, 2006"

    # Add custom assets with their paths relative to the static folder
    custom_css = []
    custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.

[[menu.main]]
    name = "South Asia"
    url  = "/southasia"
    weight = 10

[[menu.main]]
    name = "South-east Asia"
    url = "/southeastasia"
   weight = 20

[[menu.main]]
    name  = "About"
    url   = "/about/"
    weight = 30
    
[[menu.main]]
    name  = "contact"
    url   = "/contact/"
    weight = 40

[[menu.main]]
    name  = "Contact2"
    url   = "/contact/"
    parent = "contact"

[[menu.main]]
    name  = "Contact21"
    url   = "/contact/"
    parent = "Contact2"
    weight = 20

[[menu.main]]
    name  = "cOntact22"
    url   = "/contact/"
    parent = "Contact2"
    weight = 10

[[menu.main]]
    name  = "cOntact3"
    url   = "/contact/"
    parent = "contact"

[[menu.main]]
    name = "Andaman Islands"
    url = "/post/andamans/"
    parent="South-east Asia"

[[menu.main]]
    name = "Bali"
    url = "/post/bali/"
    parent = "South-east Asia"

[params.share]
    enable = true
    facebook = true
    twitter = true
    linkedin = true
    email = true

[params.privacy]
enable = true # false implies switching on tracking application, you can individually turn off applications that you don't want. If enable = true, then all tracking apps are switched off
facebook_like = true
DisqusShortname = "example"

[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "example"
    email           = "familytrips.life@gmail.com"
    instagram       = "example"
    youtube         = "@familytrips-life"
    linkedin        = "example"
    pinterest       = "familytripslife"
    #facebook        = "example"
    #twitter         = "example"
    #tumblr          = "example"
    #rss             = "Needed" # leave this to blank if you do not want RSS feed icon to appear on top
    #flickr          = "example"
    #vimeo           = "example"
    
# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true
    archives = false # This feature is yet to be implemented because of limitations in Hugo's way of working.
    search = true
    mailchimp = true
    mailchimpform = "//balaramadurai.us15.list-manage.com/subscribe/post?u=7f4183fa2fe7abe3dc9f4efad&amp;id=49a3dd3745"
    author = true

[params.slider]
    enable = true
    manual = false # Setting manual to true renders the slide selection to only those where the post has a slider=true option enabled
    num_features = 6 # The slider picks up the banner images from the N most recent posts, where num_features is N.
    
[permalinks]
    categories = "/categories/:slug/" #can be changed to "/category/:slug/"
    tags = "/tags/:slug/"

[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"
    author = "author"

[params.views]
    enable = true  # visitor badge from https://visitor-badge.glitch.me/

## DONE - Menu
## DONE - slider 
## DONE - facebook like on homepage
## DONE - category URL to work
## DONE - footer
## DONE - add tags to the footer
## TODO - some posts without banner
